trigger:
 branches:
   include:
     - master

variables:
  user: 'MJ'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Stage1'
    jobs:
    - job: 'Job1'
      steps:
      - script: uptime
        displayName: 'DispStage1'
  - stage: 'Stage2'
    jobs:
      - job: 'Job2'
        steps:
        - script: hostname
          displayName: 'DispStage2'