trigger:
 branches:
   include:
     - master

variables:
  user: 'MJ'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Stage1'
    jobs:
    - job: 'Job1'
      steps:
      - script: uptime
        displayName: 'DispStage1'
      - script: echo $V1